skorunkac/urls.py
from django.contrib import admin
from django.urls import path
from skorunkac.polls import views
from skorunkac.views import set_language


admin.site.site_header = 'Skorun Kaç?'
admin.site.site_title = 'Skorun Kaç?'


urlpatterns = [
    path('yonetim/', admin.site.urls),
    path('lang/', set_language, name='set_lang'),

    path('', views.init_poll, name='init_poll'),
    path('<int:poll_id>/', views.result, name='result'),
    path('<slug:session_slug>/', views.init_poll, name='init_poll'),
    path('<int:poll_id>/<int:page_no>/', views.questions, name='questions'),
    path('<int:poll_id>/kaynak/', views.suggest, name='suggest'),
]

skorunkac/polls/models.py
from urllib.parse import urlparse, parse_qs
from django.db import models
from django.urls import reverse
from django.db.models import Avg
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from skorunkac.cities.models import City


class Category(models.Model):
    name = models.CharField('kategori adı', max_length=100)
    description = models.CharField('açıklama', max_length=250, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'kategori'
        verbose_name_plural = 'kategoriler'


class QuestionSource(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'kaynak'
        verbose_name_plural = 'kaynaklar'


class Question(models.Model):
    question = models.CharField('soru', max_length=250)
    question_en = models.CharField('soru [EN]', max_length=250)
    question_f = models.CharField('soru (kadın versiyonu)', blank=True, null=True, max_length=250)
    question_f_en = models.CharField('soru (kadın versiyonu) [EN]', blank=True, null=True, max_length=250)
    category = models.ForeignKey(Category, verbose_name='kategori', blank=True, null=True, on_delete=models.SET_NULL)
    order = models.PositiveSmallIntegerField('sıralama', blank=True, null=True)
    inverse_score = models.BooleanField('ters skor', default=False)
    source = models.ForeignKey(QuestionSource, verbose_name='kaynak', blank=True, null=True, on_delete=models.SET_NULL)
    active = models.BooleanField('yayında', default=True)

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'soru'
        verbose_name_plural = 'sorular'
        ordering = ('order', 'id')


class Media(models.Model):
    categories = models.ManyToManyField(Category, verbose_name='kategoriler')
    url = models.URLField('bağlantı')
    description = models.TextField('tanım', blank=True, null=True)
    active = models.BooleanField('yayında', default=True)
    added = models.DateTimeField('eklenme tarihi', auto_now_add=True)

    def __str__(self):
        return self.url

    def clean(self):
        if not [bool(self.content), bool(self.url)].count(True) == 1:
            raise ValidationError('URL ya da icerik alanlari doldurulmali')
        if self.url and 'youtube.com' in self.url and 'watch?v=' in self.url:
            parts = urlparse(self.url)
            params = parse_qs(parts.query)
            v = params.get('v')
            if v:
                self.url = f"https://youtube.com/embed/{v[0]}"
            else:
                raise ValidationError('Youtube adresi geçersiz')

    class Meta:
        verbose_name = 'medya'
        verbose_name_plural = 'medya'


class Session(models.Model):
    name = models.CharField('oturum adı', max_length=100)
    slug = models.SlugField('bağlantı adı')
    type = models.CharField(
        'oturum tipi',
        max_length=4,
        blank=True, null=True,
        choices=(
            ('p', 'panel'),
            ('s', 'söyleşi'),
            ('t', 'tanıtım toplantısı'),
        )
    )
    institution_type = models.CharField(
        'oturum sahibi',
        max_length=4,
        blank=True, null=True,
        choices=(
            ('ö', 'özel şirket'),
            ('s', 'sivil toplum örgütü'),
            ('k', 'kamu kuruluşu'),
        )
    )
    employee_count = models.PositiveIntegerField('kurum çalışan sayısı', blank=True, null=True)
    woman_employee_count = models.PositiveIntegerField('kurum kadın çalışan sayısı', blank=True, null=True)
    attendee_count = models.PositiveIntegerField('etkinlik katılımcı sayısı', blank=True, null=True)
    woman_attendee_count = models.PositiveIntegerField('etkinlik kadın katılımcı sayısı', blank=True, null=True)
    city = models.ForeignKey(City, verbose_name='il', blank=True, null=True, on_delete=models.SET_NULL)
    location = models.CharField('yer', max_length=200, blank=True, null=True)
    notes = models.TextField('notlar', blank=True, null=True)
    created = models.DateTimeField('eklenme tarihi', auto_now_add=True)
    active = models.BooleanField('yayında', default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('init_poll', kwargs={'session_slug': self.slug})

    class Meta:
        verbose_name = 'oturum'
        verbose_name_plural = 'oturumlar'


class Poll(models.Model):
    session = models.ForeignKey(Session, verbose_name='oturum', blank=True, null=True, on_delete=models.SET_NULL)
    gender = models.CharField(
        _('Gender'),
        max_length=1,
        choices=(
            ('m', _('Male')),
            ('f', _('Female')),
        ),
    )
    age = models.PositiveSmallIntegerField(_('Your age'))
    education = models.PositiveSmallIntegerField(
        _('Education'),
        help_text=_('Final degree'),
        choices=(
            (0, _('No formal education')),
            (1, _('Primary School')),
            (2, _('Secondary School')),
            (3, _('High School')),
            (4, _('College')),
            (5, _('University')),
            (6, _('Masters')),
            (7, _('Doctorate / PhD')),
            (8, _('Student')),
        ),
    )
    marital_status = models.CharField(
        _('Marital Status'),
        max_length=1,
        choices=(
            ('b', _('Single / Not Married')),
            ('s', _('Has a partner / Engaged')),
            ('e', _('Married')),
            ('d', _('Widowed')),
            ('a', _('Divorced')),
        ),
    )
    hometown_size = models.CharField(
        _('Where You Grew Up'),
        max_length=1,
        choices=(
            ('k', _('Village')),
            ('i', _('Town')),
            ('s', _('City')),
            ('m', _('Metropolis')),
        ),
    )
    lifestyle = models.CharField(
        _('Life style'),
        max_length=1, blank=True, null=True,
        choices=(
            ('m', _('Modern')),
            ('g', _('Conservative')),
            ('d', _('Religious conservative')),
        ),
    )
    started = models.DateTimeField('başlangıç', auto_now_add=True, editable=False)
    ended = models.DateTimeField('bitiş', blank=True, null=True, editable=False)
    score = models.FloatField('skor', blank=True, null=True, editable=False)

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'anket'
        verbose_name_plural = 'anketler'


class Answer(models.Model):
    poll = models.ForeignKey(Poll, verbose_name='anket', on_delete=models.CASCADE)
    question = models.ForeignKey(Question, verbose_name='soru', on_delete=models.CASCADE)
    answer = models.PositiveSmallIntegerField('cevap', default=0)

    class Meta:
        verbose_name = 'cevap'
        verbose_name_plural = 'cevaplar'
        unique_together = ('poll', 'question')

skorunkac/polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.core.paginator import Paginator
from django.utils.timezone import datetime
from django.db.models import Sum, Count, Avg, F, Q
from django.utils import timezone
from django.conf import settings
from skorunkac.polls.models import Session, Question, Answer, Poll, Category


class PollForm(ModelForm):
    class Meta:
        model = Poll
        fields = ['gender', 'age', 'education', 'marital_status', 'hometown_size']


def init_poll(request, session_slug=None):
    session = None
    if session_slug:
        session = get_object_or_404(Session, slug=session_slug, active=True)

    if request.method == 'POST':
        form = PollForm(request.POST)
        if form.is_valid():
            poll = form.save(commit=False)
            poll.session = session
            poll.save()
            return redirect(
                'questions', poll.id, 1
            )

    return render(
        request,
        template_name='start.html',
        context={
            'session': session,
            'form': PollForm()
        }
    )


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['answer']


def questions(request, poll_id, page_no):
    poll = get_object_or_404(Poll, id=poll_id)
    questions = Question.objects.filter(active=True)
    p = Paginator(questions, settings.POLL_SETTINGS['QUESTIONS_PER_PAGE'])
    page = p.page(page_no)

    if request.method == 'POST':
        for question in page.object_list:
            try:
                answer = int(request.POST.get(str(question.id)))
            except:
                pass
            else:
                if answer in range(0, settings.POLL_SETTINGS['ANSWER_STEPS'] + 1):
                    Answer.objects.update_or_create(
                        poll=poll,
                        question=question,
                        defaults={
                            'answer': answer
                        }
                    )

        if page.has_next():
            return redirect(
                'questions', poll.id, page.next_page_number()
            )
        else:
            poll.ended = timezone.now()
            score = poll.answer_set.filter(
                question__inverse_score=False
            ).aggregate(total_points=Sum('answer'))['total_points'] or 0
            inverse_score = poll.answer_set.filter(
                question__inverse_score=True
            ).aggregate(total_points=Sum('answer'))['total_points'] or 0
            question_count = Question.objects.filter(active=True).count()
            inverse_question_count = Question.objects.filter(active=True).filter(inverse_score=True).count()
            poll.score = round(
                100 * (score + (settings.POLL_SETTINGS['ANSWER_STEPS'] * inverse_question_count - inverse_score)) /
                question_count / settings.POLL_SETTINGS['ANSWER_STEPS'], 1
            )
            poll.save()
            return redirect(
                'result', poll.id
            )

    return render(
        request,
        template_name='questions.html',
        context={
            'paginator': p,
            'page': page,
            'page_no': page_no,
            'answer_form': AnswerForm(),
            'poll': poll,
            'poll_settings': settings.POLL_SETTINGS,
        }
    )


def result(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    scores_by_category = {}
    answers = poll.answer_set.all()
    for question in Question.objects.filter(active=True):
        category = question.category
        answer = answers.filter(question=question, poll=poll).first()
        points = 0
        if answer:
            points = answer.answer
            if answer.question.inverse_score:
                points = settings.POLL_SETTINGS['ANSWER_STEPS'] - answer.answer
        if category in scores_by_category:
            scores_by_category[category]['question_count'] += 1
            scores_by_category[category]['total_points'] += points
        else:
            scores_by_category[category] = {
                'question_count': 1,
                'total_points': points
            }
    for cat, val in scores_by_category.items():
        scores_by_category[cat]['score'] = round(
            100 / settings.POLL_SETTINGS['ANSWER_STEPS'] * scores_by_category[cat]['total_points'] /
            scores_by_category[cat]['question_count'],
            1
        )
    scores_by_category = sorted(scores_by_category.items(), key=lambda x: x[1]['score'], reverse=True)
    session_score = Poll.objects.filter(session=poll.session).exclude(score__isnull=True).aggregate(
        avg=Avg('score'), count=Count('score')
    )
    session_score_today = Poll.objects.exclude(score__isnull=True).filter(
        session=poll.session, ended__date=datetime.today()
    ).aggregate(
        avg=Avg('score'), count=Count('score')
    )
    global_score = Poll.objects.exclude(score__isnull=True).aggregate(
        avg=Avg('score'), count=Count('score')
    )

    return render(
        request,
        template_name='result.html',
        context={
            'poll': poll,
            'score': poll.score,
            'scores_by_category': scores_by_category,
            'strongest_category': scores_by_category[0],
            'weakest_category': scores_by_category[len(scores_by_category)-1],
            'session_score': session_score,
            'session_score_today': session_score_today,
            'global_score': global_score,
            'poll_settings': settings.POLL_SETTINGS,
        }
    )


def suggest(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    scores_by_category = {}
    answers = poll.answer_set.all()
    for question in Question.objects.filter(active=True):
        category = question.category
        answer = answers.filter(question=question, poll=poll).first()
        points = answer and answer.answer or 0
        if category in scores_by_category:
            scores_by_category[category]['question_count'] += 1
            scores_by_category[category]['total_points'] += points
        else:
            scores_by_category[category] = {
                'question_count': 1,
                'total_points': points
            }
    for cat, val in scores_by_category.items():
        scores_by_category[cat]['score'] = round(
            100 / settings.POLL_SETTINGS['ANSWER_STEPS'] * scores_by_category[cat]['total_points'] /
            scores_by_category[cat]['question_count'],
            1
        )
    scores_by_category = sorted(scores_by_category.items(), key=lambda x: x[1]['score'], reverse=True)

    return render(
        request,
        template_name='suggestions.html',
        context={
            'poll': poll,
            'strongest_category': scores_by_category[0],
            'weakest_category': scores_by_category[len(scores_by_category)-1],
            'poll_settings': settings.POLL_SETTINGS,
        }
    )

skorunkac/polls/templates/base.html
{% load i18n static %}
<!DOCTYPE html>
<html>
<head lang="tr">

    {% get_current_language as LANGUAGE_CODE %}
    {% get_available_languages as LANGUAGES %}
    {% get_language_info_list for LANGUAGES as languages %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% if LANGUAGE_CODE == 'en' %}What's your score!{% else %}Skorun Kaç?{% endif %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.0/css/bootstrap.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/css/ion.rangeSlider.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/js/ion.rangeSlider.min.js"></script>

    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

</head>
<body style="background-color: #eee">


<div class="text-center mt-4">

    <a href="/">
        <img src="{% static 'skorunkac.png' %}" style="max-width:40%">
    </a>

    <div class="container">

        <div class="float-right">

            {% for language in languages %}
                {% if language.code != LANGUAGE_CODE %}
                    <a href="{% url 'set_lang' %}?lang={{ language.code }}">{{ language.name_local }}</a>
                {% else %}
                    {{ language.name_local }}
                {% endif %}
                {% if not forloop.last %} | {% endif %}
            {% endfor %}

        </div>

    </div>

</div>


{% block content %}
{% endblock %}

<div class="text-center mt-4 mb-4">

<a href="/" style="font-family: 'Cutive Mono', monospace; font-weight: 900">
    <img src="{% static 'yanindayiz.png' %}" style="max-width:30%">
</a>

</div>

{% block js %}
{% endblock %}

</body>
</html>

skorunkac/polls/templates/questions.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}


{% block content %}

    {% get_current_language as LANGUAGE_CODE %}

    <div class="container px-4">

        <div class="row mb-4">

            <h3 class="mt-4 w-100">
            {% if page_no == 1 %}
                {% trans "You can start now!" %}
            {% else %}
                {% trans "Page" %} {{ page_no }}
            {% endif %}
            </h3>

            {% if page_no == 1 %}
            <p class="lead">
            {% blocktrans %}
                You will find 20 different statements on Gender Equality.
                Swipe the scale left or right to indicate whether you agree or disagree.
            {% endblocktrans %}
            </p>
            {% endif %}

            <p class="lead">
                <em>
                    {% trans "The left of the scale shows that you “strongly disagree” and the right of the scale shows that you “strongly agree”." %}
                </em>
            </p>

        </div>


        <p class="mt-4">
            <br>
        </p>

        <form method="post" id="qForm" class="w-100">

            {% csrf_token %}

            {% for question in page.object_list %}

                <div class="row mb-0">

                    <p class="lead">

                    {% if LANGUAGE_CODE == 'en' %}

                        {% if poll.gender == 'f' and question.question_f_en %}

                            {{ question.question_f_en }}

                        {% else %}

                            {{ question.question_en }}

                        {% endif %}

                    {% else %}

                        {% if poll.gender == 'f' and question.question_f %}

                            {{ question.question_f }}

                        {% else %}

                            {{ question.question }}

                        {% endif %}

                    {% endif %}

                    </p>

                </div>

                <div class="row mb-5">
                    <div class="col-10 offset-1">
                        <input type="text" class="slider" name="{{ question.id }}" value="{% widthratio poll_settings.ANSWER_STEPS 2 1 %}" />
                    </div>
                </div>

                <div class="row mb-5 w-100">
                {% comment %}
                    <div class="btn-group btn-group-toggle d-flex w-100 justify-content-center" data-toggle="buttons">

                        {% for value, text in answer_form.answer.field.choices %}

                        <label class="btn btn-outline-info w-100 align-items-center justify-content-center">
                            <input type="radio" name="{{ question.id }}" value="{{ value }}" autocomplete="off">
                            <div class="mt-2 mb-2">
                                {{ text }}
                            </div>
                        </label>

                        {% endfor %}

                    </div>
                {% endcomment %}
                </div>

            {% endfor %}

            <button type="submit" id="x" class="btn btn-primary btn-lg float-right">Ileri</button>

            <div class="row">

                {% with ''|center:paginator.num_pages as range %}
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                    {% for _ in range %}
                        <li class="page-item {% if forloop.counter == page_no %}active{% else %}disabled{% endif %}"><a class="page-link">{{ forloop.counter }}</a></li>
                    {% endfor %}
                    </ul>
                </nav>
                {% endwith %}


            </div>

        </form>

    </div>

{% endblock %}

{% block js %}

<script>

$(".slider").ionRangeSlider({
    min: 0,
    max: {{ poll_settings.ANSWER_STEPS }},
    skin: 'big'
});

</script>

{% endblock %}

skorunkac/polls/templates/result.html
{% extends "base.html" %}
{% load crispy_forms_tags static i18n %}


{% block content %}

    <div class="container mt-4 px-4">

        <div class="row">

            <h2 class="mb-4">
                <small>
                    {% trans "Thank you for taking the time to complete our test!" %}
                </small>
                <br>
                {% trans "Your gender equality score" %}:
                <span class="text-{% if poll.score >= poll_settings.SUCCESS_SCORE %}success{% elif poll.score >= poll_settings.FAIL_SCORE %}warning{% else %}danger{% endif %}">
                    {{ poll.score }}
                </span>
            </h2>

            <div class="w-100"></div>

            {% if session_score.count >= poll_settings.DISPLAY_AVERAGE_SESSION_TODAY_THRESHOLD %}
            <p>
                {% if poll.session %}
                    {% blocktrans with poll.session as session and session_score_today.count as count and session_score_today.avg|floatformat:1 as  average %}
                        Average of <strong>{{ count }}</strong> people who completed the survey today at the {{ session }} session is {{ average }}
                    {% endblocktrans %}
                {% else %}
                    {% blocktrans with session_score_today.count as count and session_score_today.avg|floatformat:1 as  average %}
                        Average of <strong>{{ count }}</strong> people who completed the survey today is <strong>{{ average }}</strong>
                    {% endblocktrans %}
                {% endif %}
            </p>
            <div class="w-100"></div>
            {% endif %}


            {% if poll.session %}
            {% if session_score.count >= poll_settings.DISPLAY_AVERAGE_SESSION_THRESHOLD %}
            <p>
            {% blocktrans with poll.session as session and session_score.count as count and session_score.avg|floatformat:1 as  average %}
                Average of <strong>{{ count }}</strong> people who completed the survey so far at the {{ session }} session is {{ average }}
            {% endblocktrans %}
            </p>
            <div class="w-100"></div>
            {% endif %}
            {% endif %}


            {% if global_score.count >= poll_settings.DISPLAY_AVERAGE_TOTAL_THRESHOLD %}
            <p>
            {% blocktrans with global_score.count as count and global_score.avg|floatformat:1 as average %}
                Average of <strong>{{ count }}</strong> people who completed the survey so far is {{ average }}
            {% endblocktrans %}
            </p>
            <div class="w-100"></div>
            {% endif %}

        </div>

        <div class="row">

            <h3 class="mt-4">
                {% trans "Your score by categories" %}:
            </h3>

            <div class="w-100"></div>

            <table>
            {% for cat, scores in scores_by_category %}
                {% with scores.score as score %}
                <tr class="text-{% if score >= poll_settings.SUCCESS_SCORE %}success{% elif score >= poll_settings.FAIL_SCORE %}warning{% else %}danger{% endif %}">
                    <td>{{ cat.name }}</td>
                    <td class="text-right">{{ score }}</td>
                </tr>
                {% endwith %}
            {% endfor %}
            </table>

        </div>

        <div class="row mt-4">

            {% if strongest_category.1.score < poll_settings.FAIL_SCORE %}

                <h3>{% trans "Sorry, you couldn’t obtain a good score in any of the categories." %}</h3>

            {% else %}

                <p class="lead">
                {% blocktrans with strongest_category.0.name as category and strongest_category.1.score as score %}
                    Your best category is <em>{{ category }}</em>;
                    your score in this category is <span class="text-success">{{ score }}</span>
                {% endblocktrans %}
                </p>

                <div class="w-100 mt-2"></div>

            {% endif %}


            {% if weakest_category.1.score > poll_settings.SUCCESS_SCORE %}

                <h3>{% trans "Congratulations, you scored high in all categories!" %}</h3>

            {% else %}

                <p class="lead">
                {% blocktrans with weakest_category.0.name as category and weakest_category.1.score as score %}
                    Your weakest category is <em>{{ category }}</em>;
                    your score in this category is <span class="text-warning">{{ score }}</span>
                {% endblocktrans %}
                </p>

                <div class="w-100 mt-2"></div>

                {% comment %}
                <blockquote class="blockquote">
                    <strong>{{ weakest_category.0.name }}</strong> konusunda kendini geliştirmek için derlediğimiz kaynaklara göz atmak ister misin?
                </blockquote>

                <div class="w-100"></div>

                <a href="{% url 'suggest' poll_id=poll.id %}" class="btn btn-primary">Kaynakları göster</a>
                {% endcomment %}

            {% endif %}

            <p class="mt-5">
            {% blocktrans %}
                Thank you for participating and sharing your opinion.
                The data collected in this game won’t be shared with other institutions.
                Answers will be analyzed as general statistical data.
            {% endblocktrans %}
            </p>

            <div class="text-center w-100">
                <p class="lead">
                    <span class="small">{% trans "With the Contribution of" %}</span>
                    <br>
                    <img src="{% static "teknosa.png" %}" style="height: 2em">
                </p>
            </div>

        </div>
    </div>

{% endblock %}

skorunkac/polls/templates/start.html
{% extends "base.html" %}
{% load i18n crispy_forms_tags static %}


{% block content %}

    {% get_current_language as LANGUAGE_CODE %}

    <div class="container px-4">

        <div class="row">

            <h2 class="mt-5">

                {% if LANGUAGE_CODE == 'en' %}
                    Welcome to Our WHAT’S YOUR SCORE Game!
                {% else %}
                    SKORUN KAÇ oyunumuza hoşgeldin!
                {% endif %}

                <small class="text-muted">{{ session.name }}</small>
            </h2>



            <p class="lead">
                {% if LANGUAGE_CODE == 'en' %}
                    What do you think and how do you act on the role of women and men in society, work, home, family life,
                    and in their mutual relationships?
                {% else %}
                    Kadın ve erkeğin toplumdaki, iş hayatındaki, evde ve aile içindeki yeri, karşılıklı ilişkileri konusunda ne
                    düşünüyorsun, nasıl davranıyorsun?
                {% endif %}
            </p>

            <p class="lead">
                {% if LANGUAGE_CODE == 'en' %}
                    This test aims to reflect your attitude and behaviors on the subjects mentioned above.
                {% else %}
                    Bu test<sup>*</sup> SENİN bu konulardaki tutum ve davranışlarına, algına AYNA tutmayı amaçlıyor.
                {% endif %}
            </p>

            <p class="lead">
                {% if LANGUAGE_CODE == 'en' %}
                    It is important for you to express your opinions clearly and sincerely in order to reach our goal.
                    There are no questions that will reveal your identity. Our aim to understand how general public thinks and behave rather than individuals.
                {% else %}
                    Fikirlerini açık ve samimi bir şekilde ifade etmen amacımızı gerçekleştirmek açısından büyük önem taşıyor.
                    Testte kimliğini ortaya çıkaracak hiçbir soru yok. Tek tek kişilerin değil genel olarak insanların ne düşündüğünü, nasıl davrandığını anlamak istiyoruz.
                {% endif %}
            </p>

            <p class="lead">
            </p>

            <div class="text-center w-100">
                <p class="lead">

                    <span class="small">
                        {% if LANGUAGE_CODE == 'en' %}
                            With the Contribution of
                        {% else %}
                            Teknosa'nın katkılarıyla
                        {% endif %}
                    </span>

                    <br>

                    <img src="{% static "teknosa.png" %}" style="height: 2em">

                </p>
            </div>

            <p class="lead small">
                <sup>*</sup>

                {% if LANGUAGE_CODE == 'en' %}
                    While developing this test, we made use of the GEMS scale of PROMUNDO, the question bank by KONDA Research Company,
                    and the work namely “Masculinity Moods in Turkey” (“Erkekliğin Türkiye Halleri”) 2018, by Hale Bolak Boratav, Güler Okman Fişek and Hande Eslen Ziya.
                {% else %}
                    Bu testi hazırlarken PROMUNDO’nun GEMS ölçeğinden, KONDA Araştırma Şirketinin soru bankasından ve
                    Hale Bolak Boratav, Güler Okman Fişek, Hande Eslen Ziya’nın Erkekliğin Türkiye Halleri, 2018 çalışmasından faydalandık.
                {% endif %}

            </p>


            <h4 class="mt-4">
                {% if LANGUAGE_CODE == 'en' %}
                    Before we proceed, can you briefly introduce yourself?
                {% else %}
                    Başlamadan önce kısaca tanışabilir miyiz?
                {% endif %}
            </h4>


        </div>

        <div class="row">

            <form method="post">

                {% csrf_token %}

                {{ form|crispy }}

                <button type="submit" class="btn btn-primary btn-lg">{% trans "Start" %}</button>

            </form>

         </div>

    </div>

{% endblock %}

skorunkac/polls/templates/suggestions.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="container mt-4 px-4">

        <div class="row mt-4 mb-4">
            <p class="display-4"><strong>{{ weakest_category.0.name }}</strong> konusundaki kaynak önerilerimiz</p>
        </div>

        <div class="row">

        {% for media in weakest_category.0.media_set.all %}
            <div class="col">
                <iframe width="100%" height="315" src="{{ media.url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
            {% if forloop.counter|divisibleby:2 %}
                <div class="w-100"></div>
            {% endif %}
        {% endfor %}
        </div>

        <div class="row">
            <p class="mt-4">
                <a href="{% url 'init_poll' session_slug=poll.session.slug %}" class="btn btn-lg btn-primary">Tekrar başla</a>

                <a href="{% url 'result' poll_id=poll.id %}" class="btn btn-lg btn-primary ml-4">Skor sayfasına dön</a>
            </p>
        </div>

    </div>

{% endblock %}